### ISSUE TITLE
Premier événement : 22 septembre 2016 de 11h à 15h Journée Festive de Rentrée !

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#10]
Regrouper ici vos idées en ce qui concerne la journée festive de rentrée.

Nous avons pour l'instant prévu d'organiser une mini boiler mais à voir en fonction de la météo et du nombre de personnes présentes sur le stand.

Idées :
- Faire des cartes de visites >Echo en grande quantité afin que les personnes se servent. :heavy_check_mark:
- Mini Boiler 33 Tour à confirmer auprès de la vie associative. :x: 
- Musique HOUSE sur le stand. :heavy_check_mark:
- Une télé / Ecran PC avec les vidéos des LANs qui tournent en boucle afin d'attirer les personnes vers le stand. :x:
- PC à disposition si adhésion en ligne ou pas ? :x: 
- Fiches d'adhésions papiers en grand nombre. :heavy_check_mark:

**Comment by Uinelj** [comment]
- Je suis carrément pour 
- Je suis carrément pour, mais ici on a deux choix : Soit on affiche directement le côté house/deephouse, soit on fait un mix un peu plus accessible. ça aurait l'avantage de toucher plus de monde, mais le désavantage d'avoir des gens qui potentiellement seraient déçus par la prog des évènements ultérieurs.
- On a ce qu'il faut pour ça ?
- On pourra mettre un PC à disposition pour l'inscription en ligne, ça fait moins de paperasse après, mais voir #11 
- Toujours prévoir de l'adhésion papier au cas où. On pourrait même imaginer avec des gens qui se baladent dans la fac (le jour de la journée festive pas mal de monde chill autour du campus sans trop aller voir les stands), et qui proposent l'inscription en discutant.

**Comment by AlexFourgs** [comment]
- Ok, on valide les cartes de visites, par contre ce sera fait sur les fonds d'echo (faudra qu'on parle du budget toi et moi et que du coup on se fixe un nombre minimum d'adhésion le jour de la journée festive pour s'assurer de pas perdre trop de thunes).
- Je suis plus pour le premier point, on est pas la pour faire de la publicité mensongère et de vendre du faux aux étudiants. L'idée de la House / Deep House c'est que c'est "accessible" contrairement à la Techno qui peut être un peu trop violente.
- Bah on chope un écran et c'est tout, après c'est plus pour les gens qui osent pas trop demander ce qu'on fait, qu'ils aient une idée.
- Ok.
- Ok, mais il faudra des volontaires pour ça :/

**Comment by Uinelj** [comment]
Concernant le dernier point, je pensais à des gens comme Hervé ou Rébecca, qui sont souvent hypés par des trucs du style. (Même si c'est chelou entre Rebecca et moi :): )

**Comment by AlexFourgs** [comment]
Ok bonne idée, il faudra les contacter dans ce cas :)
A la limite on a un peu de marge vu que c'est pas directe à la rentrée.

**Comment by Uinelj** [comment]
Du coup update sur ce point. On nous a proposé la MDE si tu te souviens bien. J'ai trouvé que c'était une bonne idée, mais comme soulevé par @aryus96 niveau impression c'est plus cool de faire un truc sauvage. Ca montre un côté improbable et improvisé qui pourrait attirer du monde à notre table. 
- Il faut impérativement se faire une belle affiche ECHO bien grande pour montrer qu'on est des pros.

**Comment by AlexFourgs** [comment]
[URGENT] Faire les cartes de visites et la bannière rapidement.

A discuter avec Arya pour le design des cartes le plus tôt possible et lancer la commande dès que possible.

**Comment by AlexFourgs** [comment]
Mockup des cartes de visites + banderole présenter demain puis commande.

**Comment by arya-coding** [comment]
Il nous faut impérativement les deux éléments suivants, pour la journée festive ainsi que les mix sauvages.

Deux modèles différents :

![tente](https://cloud.githubusercontent.com/assets/9800251/18350555/be2d21be-75d6-11e6-9f88-f43bf04c4919.PNG)

![captzzzure](https://cloud.githubusercontent.com/assets/9800251/18350587/de80a152-75d6-11e6-9ae4-e90d9d6919d8.PNG)

Enfin, à voir si on a pas déjà :

http://www.castorama.fr/store/Enrouleur-de-bricolage-3G1-30-metres-prod18980007.html?navAction=jump&isFeaturedProduct=true&navCount=0&categoryId=cat_id_1205

![sddfcapture](https://cloud.githubusercontent.com/assets/9800251/18350672/39b10da0-75d7-11e6-9152-15d2637331f2.PNG)

De plus, mon ami fait à 5€ la location de sa machine à fumée pour l'event ! Juste le prix du liquide quoi
![caqsdqspture](https://cloud.githubusercontent.com/assets/9800251/18350848/1cdc925c-75d8-11e6-91ca-b5633e030451.PNG)

**Comment by Uinelj** [comment]
Je suis pas sûr que la machine à fumée soit nécessaire :/

**Comment by arya-coding** [comment]
C'est comme le giro de faja, on pense que c'est pas utile, mais au final oui.
Ca rajoute de l'ambiance, du visuel sur le stand et du professionnalisme.

A 5€ la location... Je pense que c'est rentable !

**Comment by AlexFourgs** [comment]
# Je close cette issue.

Voici le récapitulatif des choses qui seront fait pour la journée :
- Stand avec bannière Echo
- Cartes de visites sur le stand (200) + distribution (250)
- Musique sur le stand
- Fiches d'adhésions
- Bonbon et conneries dans le genre

Les quelques détails à revoir :
- Tente de stand ?
- Mix ?
- Machine à fumée ?

**N'hésitez surtout pas à partager vos idées si vous en avez !**

**Comment by Uinelj** [comment]
Pourquoi la close si il nous reste des détails à discuter ?

**Comment by akkes** [comment]
TIL: https://www.u-cergy.fr/fr/vie-etudiante/culture/la-33-tour.html

> En première partie, le BDE Echo propose un boiler room (tech house)

**Comment by Uinelj** [comment]
On s'est désistés au dernier moment, craignant de faire un bide :)

**Comment by akkes** [comment]
Pensez à faire remonter l'erreur pour pas hyper les gens pour rien ;-)

**Comment by Uinelj** [comment]
En vrai je sais pas.. Il faut voir avec @AlexFourgs mais si on a été annoncés.... ;)

**Comment by arya-coding** [comment]
Bon.. du coup, machine à fumée ou pas ?

**Comment by AlexFourgs** [comment]
Franchement ça me fait hésiter, on en rediscutera vraiment vendredi avec la vie culturel. Si on est annoncé et que c'est possible, pourquoi pas mais je veux pas être sur la scène, je veux être en bas proche des étudiants.

**Comment by Uinelj** [comment]
Je suis d'accord. De plus, Jeudi on fait notre première cadence sauvage, ce qui nous permettra de juger de notre aptitude à faire cet événement.
