### ISSUE TITLE
Se renseigner sur la légalité d'une inscription en ligne.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Meta#11]
Je me demande si on peut proposer une inscription en ligne sans avoir de signature du mec.

A mon avis on sera quand même obligés de faire signer le bonhomme..

**Comment by Uinelj** [comment]
cc @akkes legalnazi

**Comment by akkes** [comment]
AFAIK c'est possible. En gros les textes disent qu'une signature d'un document avec pgp est équivalente à une signature à la main.
SFR utilise une signature électronique mais ils ne m'ont rien demandé du coup j'ai un doute sur la légalité de leur méthode.

**Comment by Uinelj** [comment]
D'accord, donc en gros si on a un formulaire qui store le tout dans une db, et le mec qui physiquement donne 5€, on est théoriquement dans les clous. Merci :)

**Comment by akkes** [comment]
Si t'as pas besoin de la signature oui. Là à moins que tu fasse signer au bureau y'a pas de signature de l'adhérent :-/

**Comment by Uinelj** [comment]
Hm, oui, tu as raison. Je pense qu'on a besoin d'une signature. Donc si on veut faire un truc en ligne il nous faut quand même nous coltiner une inscription papier à ton avis ?

**Comment by akkes** [comment]
Oui, on va devoir se coltiner l'inscription papier.

Je sors de la lecture du [texte](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000399095&dateTexte=&categorieLien=id) et de son [décret d'application](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000000404810&dateTexte=&categorieLien=id). En tordant la définition de signature électronique "[Lorsqu'elle est électronique, elle consiste en l'usage d'un procédé fiable d'identification garantissant son lien avec l'acte auquel elle s'attache.](https://github.com/steeve/france.code-civil/blob/master/Livre%20III/Titre%20III/Article%201316-4.md)" on pourrait dire que l'IP peut être utilisée comme signature électronique en magouillant un peu vu que c'est plus ou moins considéré comme une données personnelle. Mais ça doit aller à l'encontre de l'esprit de la loi. C'est probablement comme ça que les boites font de la signature sans chiffrement. Les signatures électroniques sécurisées correspondent juste à un équivalent de PGP.

**Comment by AlexFourgs** [comment]
Ok. Du coup papier ou pas papier ? x)

**Comment by akkes** [comment]
Papier, on se renseignera en détail en faisant le site des assos

**Comment by AlexFourgs** [comment]
Merci Louis ! :)

Donc je propose Louis dans le bureau comme juriste informatique :p

**Comment by akkes** [comment]
Haha! J'aurai un pote juriste que je lancerai un podcast droit & informatique 😆

**Comment by AlexFourgs** [comment]
Ah ! Et si on a une tablette éventuellement ? Avec une signature faite dessus, c'est éligible ?

**Comment by akkes** [comment]
Je ne pense pas qu'on puisse considérer une tablette comme [un appareil sécurisé](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006071154&idArticle=LEGIARTI000022365386&dateTexte=&categorieLien=cid). Donc non :-(

**Comment by AlexFourgs** [comment]
Ah oui je vois, à mon avis ils considèrent que les appareils sécurisés sont les petites tablettes que les pros ont comme les facteurs & inc...

**Comment by AlexFourgs** [comment]
Du coup c'est mort ?

**Comment by akkes** [comment]
Je pense 😞

**Comment by AlexFourgs** [comment]
Ok :/ 
Après pendant 3 ans on a fait ça au format papier, ça demandera un peu de temps mais c'est pas grave.

Je close l'issue.
