### ISSUE TITLE
Simplifier le nouveau formulaire d'adhésion.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#12]
Dès que je retrouve le formulaire, je pense qu'il serait intéressant de le simplifier et d'ajouter éventuellement des champs (par exemple pour des personnes qui seraient intéressaient pour rejoindre Echo).

**Comment by akkes** [comment]
Une fiche d'inscription actuelle anonymisé: ![ficheinscription](https://cloud.githubusercontent.com/assets/1679348/17479066/7f9f763c-5d70-11e6-8c96-2be44b442f75.png)

**Comment by AlexFourgs** [comment]
Merci Louis !
- A retirer :
  - Téléphone
- A ajouter :

Merci de confirmer svp.

**Comment by akkes** [comment]
3 étapes ça me semble long aussi

**Comment by AlexFourgs** [comment]
## Alpha
- Partie 1 (à conserver)
  - Nom
  - Prénom
  - Sexe
  - Date de naissance
  - Email
  - Portable
  - Partie complète signature + ajouter une case pour les droits à l'image
- Partie 2 (à donner à l'adhérent)
  - Nom
  - Prénom
  - Cotisation

# à valider rapidement pour que je puisse présenter un mockup Jeudi à la réunion.

**Comment by Eresia** [comment]
Y aurait moyen après de récup le fichier source ? :D

**Comment by AlexFourgs** [comment]
Haha, M. veut récupérer la feuille d'adhésion pour Hazybot ? :p

Je te passerai ça :) T'aura juste à remplacer le logo par celui d'Hazibot et le titre :)

**Comment by AlexFourgs** [comment]
[Adhesion_20162017_alpha.pdf](https://github.com/bdeecho/Meta/files/458888/Adhesion_20162017_alpha.pdf)

Voila la version alpha du nouveau formulaire. Il manque encore la partie cotisation.

**Comment by AlexFourgs** [comment]
[Adhesion_20162017_beta.pdf](https://github.com/bdeecho/Meta/files/462088/Adhesion_20162017_beta.pdf)

Voila la version beta du nouveau formulaire. Il manque la note légale. 

On ajoute la note légale ou pas ?

Merci de confirmer rapidement afin de cloturer cette issue et de pouvoir lancer l'impression des fiches d'adhésions.

**Comment by akkes** [comment]
Tu entends quoi par "note légale"?

**Comment by AlexFourgs** [comment]
Ce qui il y a écrit tout en bas sur l'ancien formulaire.

**Comment by akkes** [comment]
Si on fait un traitement informatique il faut le dire: https://fr.wikipedia.org/wiki/Loi_informatique_et_libertés#Le_droit_d.27information

Et c'est l'article 40 pour le droit à la rectification: https://fr.wikipedia.org/wiki/Loi_informatique_et_libertés#Le_droit_de_rectification

Et puis ça me semble utile. Si jamais ça rentre pourquoi ne pas le mettre?

**Comment by AlexFourgs** [comment]
Bon du coup je vais la rajouter.

En ce qui concerne les informations, cela suffit dans le formulaire ? Pas de numéro étu ou d'adresses d'après vous ?

**Comment by akkes** [comment]
Le but c’est de pouvoir les identifier en cas de besoin non? Dans ce cas je ne vois pas pourquoi on aurait besoin de telles informations

**Comment by AlexFourgs** [comment]
Merci Louis ^^

**Comment by AlexFourgs** [comment]
[Fiche_adhesion_echo_2016_2017.pdf](https://github.com/bdeecho/Meta/files/462367/Fiche_adhesion_echo_2016_2017.pdf)

Le nouveau formulaire d'adhésion à Echo.

Validé ?

**Comment by arya-coding** [comment]
Vu & validé pour ma part.

Merci du travail, beau boulot.

**Comment by Uinelj** [comment]
En A5 c'est possible ? Histoire d'en avoir 2 par feuille.

**Comment by AlexFourgs** [comment]
C'est déjà fais ;) 

https://github.com/bdeecho/Meta/blob/master/Fiche_adhesion_echo_2016_2017_demifeuille.pdf

**Comment by arya-coding** [comment]
Nickel, de plus, c'est plus pratique pour classer et ranger ça.

**Comment by AlexFourgs** [comment]
Du coup je close l'issue. Merci pour votre aide !
