### ISSUE TITLE
Liste de courses

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#14]
## Liste de courses pour demain
- Général
  - Cafetière
  - Bouilloire
  - Balai
  - Filtres à café
  - Micro Onde ?
- Nourriture / Boisson
  - Canettes (Coca, Coca Cherry, Oasis Tropical, Ice Tea Pêche, 7up Mojito)
  - Café
  - Barres chocolatées (Mars, Snickers, Twix, Bounty)

**Comment by Uinelj** [comment]
- Barres type Snickers/Mars ?
- Micro-ondes ?
