### ISSUE TITLE
Liste des choses à dire pour la réunion avec la vie associative. (Réunion du 16 Septembre)

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#17]
- **Réunion le 16 septembre de 9h30 à 10h30 bureau 216 MDE des chênes**
- Parler du calendrier et des lieux
- Événements gratuits ou 5€ + conso pour éviter les désistements (système d'inscription en ligne à l'événement, FIFO, places réservés adhérents, places réservés étudiants, le reste pour public extérieur)
- Nouveaux contacts
  - Prestataires
  - Artistes / Labels
  - Collectif (chineurs si on y arrive)
- Voir pour la sécurité
- Parler des stands de préventions
- Parler de la mise en place de SAM (bracelet, petit avantages)
- Nouveau petit projet : Afterwork Openmix 33 Tour.
- Demander si on doit remettre le même budget que précédemment pour la prochaine demande de sub
## Mail d'Aline :

> Bonjour,
> 
> Suite à la réunion technique du 11/07/2019, nous vous confirmons que votre projet sera  représenté à la commission du 30/09/2016 pour un complément d’information (l’horaire vous sera communiquée ultérieurement si vous avez des indisponibilités merci de le faire savoir dès maintenant), la présence de l’association est obligatoire.
## Plan du discours
- Rappel sur ce qu'est Echo et ses objectifs (promotion de la musique électronique sur l'UCP, partage, communautés...)
### Événements
- "projet boiler" :
  - Nouveau nom : Cadence
  - Nouveaux contacts, dans l'ordre : Pont Neuf (TAOS), Décisions Acoustiques (Surpr!ze), Chineurs de Paname.
  - Au vu de nos contacts et de l'engoument : 33 Tour pas assez grande. Nouveau lieu.
  - On vise 350, en fonction du lieu (Rotonde ? Hall Chênes 1 ?)
  - On a commencé à démarcher pour la croix-rouge, le planning familial etc.
  - Gros problème : La sécurité. On s'organise comment ?
  - Horaires ? On pense à 20h-2h (ou 19h-01h) : VOIR SI ON PEUT PAS ORGANISER DU COVOIT
  - Vestiaire
- Cadences sauvages 
  - Evènements improvisés dans le local, ou a la MDE
- Afterwork Open mix
  - Evènements en début de soirée, petite tise, 
  - Un minimum thématisé
  - Tout le monde peut mixer en s'inscrivant sur la liste
  - Ramenez vos vinyles/Clé USB :)
- Matériel DJ semi-pro à disposition des adhérents au local en journée
  - Découverte / Entraînement et partage de techniques de mix,
  - Ambiance...
### Matériel nécessaire
- Matériel DJ semi-pro.
  
  Il sera utilisé lors des afterwork open mix, des cadences sauvages et mis à disposition des adhérents curieux en journée.

**Comment by arya-coding** [comment]
N'oubliez pas de parler également de la décoration.

**Comment by Uinelj** [comment]
Je crois que la réunion ne concerne que les cadences, mais on pourrait l'évoquer.' ?

**Comment by arya-coding** [comment]
Et bien pour les questions de sécurité et de limitation de la décoration ? C'est ce que l'on avait dis, non ?

**Comment by AlexFourgs** [comment]
Théoriquement, la réunion est une "réunion technique pour le projet "Boiler"", après on compte bien présenter notre nouveau projet d'Afterwork Open Mix (même si c'est plus ou moins lié).
Ça ne nous coûtera rien de juste poser la question en fin de réunion pour la décoration afin de savoir auprès de qui il faut se renseigner pour la sécurité & inc...
