### ISSUE TITLE
Secret Santa

### ISSUE THREAD

**Issue by akkes** [bdeecho/Meta#18]
Pour organiser le secret santa mentionné pendant la réunion il faut:
- Choisir une date au moins une semaine avant les vacances de Noël/Nouvel-an et y réserver la mde
- définir qui reste pour la permanence de dépôt/reprise des cadeaux (1 semaine avant/après)
- valider les textes (il faut probablement rappeler les détails de la semaine de dépôt/reprise des cadeaux)
- tester le script (filage)

Pour les textes (les réponses obligatoires sont en italique:
# Secret Santa >Echo

Voici venu l'heure de l'échange de cadeaux d'Echo. Une fois le tirage au sort effectué tu aura jusqu'au [DATE À FIXER] pour lui trouver un cadeau.

_Prénom_:
_Nom_:
_Courriel_:
Des suggestions ou des propositions pour ton père Noel?:
Des trucs à éviter?:
_Rassure moi, tu as été sage cette année?_: Très vilain <-> Plutôt sage
# Secret Santa >Echo

OK, bien reçu!

Une fois le tirage au sort effectué tu recevra les coordonnées de ton protégé par mail. Si il a été gentil, tu aura même des propositions de sa part. Tu aura alors jusqu'au [DATE À FIXER] pour lui trouver un cadeau.

![capture d ecran 2016-09-08 a 11 13 40](https://cloud.githubusercontent.com/assets/1679348/18343846/586ead82-75b5-11e6-880d-158f34ddb4dd.png)

**Comment by akkes** [comment]
Pour la temporalité je propose:
- 1 semaines d'inscription de sorte que l'on annonce l'event fin novembre/début décembre. Le 24 novembre pourrait être une bonne date.
- Tirage (ici le 1er décembre)
- 2 semaines de recherche/achats de cadeaux/dépôt au local
- une journée d'échange organisé (ici le 15 décembre)
- les absents récupèrent leur cadeau après les vacances

D'après le calendrier scolaire les vacances de fin d'années commencent le samedi 17 Décembre. J'ai calé les dates ci-dessus sur cette donnée

**Comment by Uinelj** [comment]
Ca me va très bien ! :)
Peut-être en glisser un mot à Valérie Rame ? C'est un projet intéressant et personne ne l'a fait sur le campus.

**Comment by akkes** [comment]
Pourquoi ne pas faire ça pendant la réunion du 16? (cf #17)

**Comment by Uinelj** [comment]
La réunion du 16 concerne, corrige moi @AlexFourgs si je me trompe, le projet Boiler uniquement.

**Comment by akkes** [comment]
Il me semble qu'il a été fait mention de poser d'autres question? Et puis ça n'avait pas gêné qu'on parle d'autres choses lors de la réunion pour la semaine culturelle l'an dernier. Tant que cela ne prend pas 3h

**Comment by Eresia** [comment]
Au moins en parler avec Valérie Rame à la fin de la réu je pense que c'est possible.

**Comment by akkes** [comment]
J'ai commencé à remplir la demande de manif. Quelques questions:
- Vu qu'on fait cadence de 16 décembre, faudrait peut-être décaler la remise vu qu'elle était prévue le 15?
- On trouve un joli nom autre que Secret Santa?
- On fait un test grandeur-nature du script avant?
- On fait l'échange en même temps que https://github.com/bdeecho/Chaudiere/issues/30 ?

Pour la remise de cadeaux elle-même, je pensais la faire à la MDE Saint-Martin. On garde les cadeaux derrière le comptoir pour ceux qui ne peuvent pas être là pendant. on pourrait éventuellement faire un écran qui affiche le statut des cadeaux?

[Déclaration de manif Secret Santa.docx](https://github.com/bdeecho/Meta/files/561768/Declaration.de.manif.Secret.Santa.docx)

**Comment by Uinelj** [comment]
- Yes pour décaler la remise
- SecretSanta c'est sympa, après je sais que LifeUp fait aussi un secret santa, donc on pourrait trouver un nom mais bon.. 
- Bien entendu !
- L'échange = la remise ?

**Comment by akkes** [comment]
- Vu que la cadence est décalée, On maintient le 16 décembre?
- Bah ce serai cool, histoire d'éviter l'ambiguïté
- Inscrivez vous ici pour le test: https://docs.google.com/forms/d/e/1FAIpQLSdr4PKdY6jFb6QNBlGLydJIg_t3QNpp20bduxL9QuzSacb-vQ/viewform
- Oui échange = remise

**Comment by akkes** [comment]
Remise le 3 Janvier (on a pas cours en FI).
Inscription jusqu'au Lundi 5 dec.
Je sais pas qui gère bdeecho.fr mais faudrait un redirect bdeecho.fr/secretsanta -> https://docs.google.com/forms/d/e/1FAIpQLSdr4PKdY6jFb6QNBlGLydJIg_t3QNpp20bduxL9QuzSacb-vQ/viewform
c'est possible dans la soirée?

**Comment by Uinelj** [comment]
[secretsanta.bdeecho.com](http://secretsanta.bdeecho.com/)

**Comment by akkes** [comment]
[secretSanta.pdf](https://github.com/bdeecho/Meta/files/614502/secretSanta.pdf)
