### ISSUE TITLE
Hackathon

### ISSUE THREAD

**Issue by akkes** [bdeecho/Meta#19]
Ce serai cool d'avoir un event hackathon pour le coté info d'>Echo. Genre un truc sur une soirée. Éventuellement en parler avec des profs pour qu'ils nous aident sur le choix des épreuves.

[L'objectif](https://www.youtube.com/watch?v=uxKmDWDUZ5A)

@AlexFourgs parlait de le mettre sous la marque Versity

**Comment by AlexFourgs** [comment]
Du coup ouai, Versity représenterait vraiment le pôle informatique d'Echo.

L'idée d'Hackaton est juste génial, c'est ce côté purement informatique qui manque chez Echo !

Perso je valide à 200%

**Comment by Uinelj** [comment]
Pour moi Versity ce sont des LAN et rien d'autre, mais on peut en discuter..

**Comment by AlexFourgs** [comment]
Bah après tu peux mettre "Versity Hackaton # 1" c'est pas un problème.

**Comment by akkes** [comment]
éventuellement on prend comme nom si on trouve pas mieux?

Du coup je pense qu'il faudrait un truc accessible à des Licences. Éventuellement un jeu en pseudo-ASM ou l'objectif de faire quelque chose en une soirée?

**Comment by AlexFourgs** [comment]
https://www.youtube.com/watch?v=uxKmDWDUZ5A

ça avec l'alcool en moins ! Ton idée est juste géniale !

**Comment by Uinelj** [comment]
D'un côté associer ça à Versity ça peut être sympa parce que ça peut concerner la même cible. D'un autre Versity ça a été vendu comme étant du gaming et de l'ouverture aux autres..

On pourrait imaginer un nom genre echo.hack ?

**Comment by akkes** [comment]
J'avais songé à des noms inspirés de drogue pour évoquer le coté _flow_ du hack (genre Sp33d)
Mais l'idée d'une sorte d'url peut-être interessante.

J'aimerai tenter de garder le coté ouvert, limite faire découvrir le truc. Mais on risque de ne pas avoir d'effet Social Network dans ce cas (mais soyons honnêtes: on a peu de chances de l'avoir de toute façon)

**Comment by Uinelj** [comment]
Le côté _flow_ ?
La drogue étant pas légale, je suis pas sûr que l'université verrait d'un bon oeil une allusion aussi directe..

**Comment by akkes** [comment]
Tu vois Super Hexagon, Duet, Hotline Miami? Ils ont pour objectif de te mettre en [flow-state](https://fr.wikipedia.org/wiki/Flow_%28psychologie%29). Gamasutra a un très bon [article](http://www.gamasutra.com/view/feature/166972/cognitive_flow_the_psychology_of_.php) pour comprendre le flow dans un jeu.

**Comment by Uinelj** [comment]
C'est la "zone", si je comprends bien.

**Comment by akkes** [comment]
Oui, c'est bien ça! Je ne trouvais plus le terme français désolé 😔

**Comment by AlexFourgs** [comment]
Du coup :
- Il faut voir avec Tram pour nous soutenir et donner des idées
- Trouver une date
- Trouver un lieu

Une petite idée qui me vient à l'esprit, pour hack j'imagine que dans certains cas il est nécessaire d'agir physiquement sur le système (branchement de cables, conneries dans le genre), pourquoi ne pas faire une hackaton avec un délire de "chasse au trésor" dans le sens ou lorsqu'il faut agir sur le système physiquement, certains hack permettent d'obtenir des indices sur l'emplacement du système dans la fac ?

**Comment by Uinelj** [comment]
C'est une très très bonne idée !

On pourrait limite organiser un cicada-like.

**Comment by AlexFourgs** [comment]
Bon j'attend la réponse de @akkes, après il faudrait écrire un petit dossier pour présenter cette idée d'événements que l'on pourra envoyer au département informatique et à certains profs en particulier en leur demandant de l'aide et du soutien éventuellement dans la réalisation.

Une fois cela fait on pourra se permettre de lancer le projet au niveau de la vie associative et nous organiser.

On parle de deux LANs cette année, pourquoi ne pas faire aussi deux hackatons ?

Point perso, ce projet m'intéresse énormément, il me fait un peu penser au concept des escape game, il permettra à certains étudiants d'approfondir leurs connaissances, et surtout de faire vivre le pôle informatique de l'UCP qui est vraiment mort point de vue vie associative... Et quand on sait que les profs sont vraiment cool et apprécient énormément ces initiatives, c'est tout bénef !

**Comment by AlexFourgs** [comment]
Du coup on bascule le projet hackaton dans le dépôt "Versity" ;)
