### ISSUE TITLE
Repenser le logo Echo.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Meta#2]
Le logo de l'association ne correspond plus vraiment à l'orientation qu'on compte lui faire prendre. 
Il faut d'ores et déjà commencer à réfléchir à un nouveau logo pour Echo.

**Comment by AlexFourgs** [comment]
J'avais pensé à un vinyle à la place du O (classique) et on garde le chevron pour le côté informatique.

**Comment by Uinelj** [comment]
Yep, de souvenir c'est ce dont on avait discuté IRL. A voir qui pourrait élaborer le logo ?

**Comment by AlexFourgs** [comment]
Arya ? Je lui en avait parler, il m'a dis qu'il le ferait, faut que je lui en reparle.

**Comment by AlexFourgs** [comment]
Je close ici :)
