### ISSUE TITLE
Décoration du local

### ISSUE THREAD

**Issue by arya-coding** [bdeecho/Meta#20]
Bonjour,

Je vous présente aujourd'hui les items de la décoration du local.

![capture](https://cloud.githubusercontent.com/assets/9800251/18344494/d3876fca-75b7-11e6-9882-3627e8224dde.PNG)

![captu1re](https://cloud.githubusercontent.com/assets/9800251/18345202/c25b4138-75ba-11e6-925b-30fd39e14a20.PNG)

![1231capture](https://cloud.githubusercontent.com/assets/9800251/18346052/a75b0d42-75be-11e6-9303-c4fecc0cbc8b.PNG)

Pour le poisson rouge, nous verrons sur place car les prix ne sont pas du tout précis, les boutiques intéressantes sont Truffaut & Animalis.

**Comment by AlexFourgs** [comment]
Voir avec la vie associative + sécurité si toutes ces choses sont possibles.

**Comment by AlexFourgs** [comment]
En tout cas, l'idée des coussins + tapis + rideau + lampe pour si peu chère changerait totalement le local !
Un seul tapis au milieu suffirait non ?

**Comment by arya-coding** [comment]
En effet, un seul tapis pourrait suffire, si on voit qu'il en faut un deuxième, on en prendra un. Mais je suis d'accord.

**Comment by arya-coding** [comment]
UPDATE :

A voir pour mettre quelques images hipster, techno, house etc, qu'on imprimerais/plastifirais pour décoration.

Enfin,

Mini extincteur :  (Il est petit, les classiques sont 6 à 9x plus gros)
![caqsdqsdpture](https://cloud.githubusercontent.com/assets/9800251/18638551/df7568b4-7e90-11e6-9156-089f1245ee44.PNG)
http://www.medisafe.fr/securite-incendie/extincteur/abc-poudre/extincteur-poudre-abc-1kg.html?gclid=CjwKEAjwmf6-BRDi9fSN7Ijt1wUSJAASawcjc57zPEVbDu6Uvcdt3d29gBoksdOs0agDKCSYWWQ5WxoCvarw_wcB
En permanence dans le local, et a emporter lors des cadences ,( mettre à côté du matériel DJ).

**Comment by Uinelj** [comment]
Il y en a déjà dans la fac, c'est pas à nous de les acheter.

**Comment by arya-coding** [comment]
Nous avons du matériel particulier, autant en prendre soin.
On doit être paré à tout, et comme je l'ai dis il nous servira pour les événements.

De plus, cela favorisera la demande des rideaux et tapis si nous montrons que nous faisons attention à la sécurité du local.

Et cela ne coûte que 20€(FDP inclus).

**Comment by Uinelj** [comment]
On a déjà du personnel qui s'occupe de la sécurité incendie pendant l'événement !

**Comment by arya-coding** [comment]
C'est toujours prévoyant. Arrêtez un feu à son départ. On est jamais trop prudent. C'est aussi petit qu'une bouteille de 1,5L d'eau hein.

**Comment by Uinelj** [comment]
Il faut demander à la sécu d'abord. Pas sûr qu'on ait même le droit d'en disposer, au vu des contrôles que ça impose.

**Comment by AlexFourgs** [comment]
@aryus96 tu peux me faire la commande finale stp, on doit rendre la demande de subvention pour vendredi avant 12h

**Comment by Uinelj** [comment]
![daewoo](https://cloud.githubusercontent.com/assets/4410814/18781153/e82f2aa6-8180-11e6-8d78-c147ef6dcdec.PNG)
