### ISSUE TITLE
Définir les avantages d'être adhérent.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#21]
_En italique les idées à reconfirmer et/ou en fonction de l'obtention du matériel adéquat_
# Local
- Canettes à 60cts.
- Friandises et biscuits à 60cts.
- Café, thé gratuit toute l'année.
- _Matériel DJ (2_CDJ + 2_ Platine vinyle + table de mixage) à disposition._
- _Station de chargement USB pour les portables_
# Events
- Prioritaire sur les inscriptions aux événements.
- _Meilleurs prix_ ou _avantages en nature (double conso offerte par exemple ?)_

**Comment by arya-coding** [comment]
Friandises et biscuits aussi à 60cts.

Une autre idée pour l'avantage adhérent, qui n'est pas pressé (à voir en fonction du budget), c'est de pouvoir charger son téléphone au local grâce à ça !  On achète également des cables.
On le pose au niveau du bureau
![sdsdcapture](https://cloud.githubusercontent.com/assets/9800251/18351151/4e6b913c-75d9-11e6-86fa-792520013ba1.PNG)

**Comment by Uinelj** [comment]
C'est une bonne idée @aryus96 , mais je me demande si ça ferait pas un peu partie de la déco du local ! Ou de son "aménagement".

**Comment by AlexFourgs** [comment]
De la déco ? dans quel sens ?

**Comment by Uinelj** [comment]
Pour mieux faire passer la pilule on peut parler d'aménagement plus que de décoration. Et ce hub USB c'est plus de l'aménagement/agrément qu'un avantage adhérent, non ?

**Comment by AlexFourgs** [comment]
Ouai mais c'est pas bête comme idée, dans le sens ou être adhérent te permet d'avoir accès à ces aménagements.

**Comment by akkes** [comment]
faut penser au câbles si on propose le rechargement de tel:
- microUSB
- iPhone
- vieux iPhone
- usbC

**Comment by arya-coding** [comment]
1x USB C
1x Lightning (iPhone)
3x microUSB
Ou bien
1x USB C
2x Lightning (iPhone)
2x microUSB

**Comment by AlexFourgs** [comment]
Il faudrait que ces avantages soient définis pour le 22 septembre afin qu'on puisse les "vendre" aux potentiels futur adhérents :)

**Comment by AlexFourgs** [comment]
Aucunes autres idées ? Vu qu'on a les adhésions à partir de demain ce serait bien qu'on puisse en vanter les mérites sur la page facebook afin de prévenir que les étudiants peuvent venir adhérer

**Comment by akkes** [comment]
Y'a quoi comme avantages à être adhérents des autres assos?
Pourquoi on veut des adhérents?

**Comment by AlexFourgs** [comment]
Avantages similaires (prix canette, café gratuit &  inc, même si on a les prix les plus bas de la fac). 
Avantages sur le prix des entrées en soirée et aux événements. Sauf que nos événements sont tellement peu chère que bon on peut pas vraiment  dire prix moins chère. 

Pourquoi on veut des adhérents ? Visibilité sur l'ensemble de la fac, arguments auprès de la vie associative, et même auprès des partenaires extérieurs. Remplir un peu les caisses d'Echo.

**Comment by Eresia** [comment]
Les adhérent sont prévenus (mail ou SMS) directement à l'ouverture des inscriptions de chaque nouvel évent ?

**Comment by Uinelj** [comment]
Les adhérents ont une priorité sur les inscriptions, ont accès à du matériel semi-pro de mix et peuvent avoir la chance de mixer à nos afterworks.

**Comment by AlexFourgs** [comment]
@Eresia Je pense qu'on profitera à chaque inscription pour ajouter le mail au groupe d'adhérents sur gmail afin de les prévenir en avance et en priorité.

Très bonne idée !

**Comment by akkes** [comment]
HS: Faites gaffe avec l'envoi de courriel en masse. Vous risquez d'être vite marqués comme spammeurs. Je ne connais pas bien les limites, genre avec moins de 100 personnes ça pourrait passer, mais pensez à vérifier avec @antoine qui me semble en avoir déjà fait. Éventuellement déporter le boulot sur Moussaillon.

**Comment by akkes** [comment]
Éventuellement on limite les afterwork aux adhérents? Quitte à faire des Cadences Sauvages pas longtemps avant pour hyper et augmenter le nombre d'inscrits? Et comme proposé par uj, on [stream pour les non-adhérents](https://github.com/bdeecho/Chaudiere/issues/18).

**Comment by AlexFourgs** [comment]
Éventuellement, mais si on fait ça en lieu public (barrabuda) on pourra pas privatiser, et si on fait ça à la 33 tour je trouverai ça dommage de dire aux étudiants curieux qu'ils peuvent pas entrer découvrir parce qu'ils ne sont pas adhérents...

**Comment by Uinelj** [comment]
Pour moi les afterwork sont des événements qui nous coûtent rien, qui sont faciles à préparer et qui ont pour vocation de nous faire connaître et de faire connaître notre concept.

En vérité, les Afterwork touchent deux publics : 
- L'étudiant lambda qui veut décompresser après les cours, en buvant une bière avec ses potes dans une ambiance sympa,
- L'étudiant intéressé par la musique électronique, et par le DJing, qui voit pour lui l'opportunité de se produire devant une scène réduite.

Je ne vois pas de raison de rendre ces événements privés.

**Comment by akkes** [comment]
Ce serai cool d'avoir une affiche qui fait un récap des avantages à afficher dans le local

**Comment by arya-coding** [comment]
Bonne idée Louis, je le fais d'ici peu.

**Comment by Uinelj** [comment]
A ajouter, comme discuté IRL avec @AlexFourgs : Une cannette de bienvenue lors de l'adhésion.
