### ISSUE TITLE
Faire le trombinoscope

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#22]
Demander qui souhaite être sur le trombinoscope.
# Liste des membres qui souhaitent être sur le trombinoscope
- Alexandre F, Président
- Julien A, Vice Président, Trésorier

**Comment by arya-coding** [comment]
Une première version, j'attends les autres personnes. Je mets juste le prénom car c'est plus friendly.
![1ere version](https://cloud.githubusercontent.com/assets/9800251/18351942/88a7c7a0-75dc-11e6-9ff3-6e1b034279d5.jpg)

**Comment by AlexFourgs** [comment]
![14206218_10210006607023029_3147182465101835809_o](https://cloud.githubusercontent.com/assets/15659639/18356647/ebd091de-75ed-11e6-9558-3598909fade1.jpg)

**Comment by AlexFourgs** [comment]
Personnes du groupe facebook manquantes sur le trombi :
- Johan Cloots
- Alexis Aktor (Secrétaire ?)
- Roxane Poupart (Photographe ?)
- Louis Desportes (Co-responsable Versity ?) @akkes 
- Vincent Monot (pour le coup c'est du pure staff versity donc pas forcément nécessaire sur le trombi)

**Comment by arya-coding** [comment]
![1ere version](https://cloud.githubusercontent.com/assets/9800251/18367882/7cde5830-761d-11e6-93f5-2d0cff822553.jpg)

Quelqu'un pourrait demander à Louis et Vincent personnellement ?

**Comment by ghost** [comment]
Il faudrait une autre photo pour Sofiane, sa tête est coupée par une ligne blanche.
Peut-être regrouper les postes complémentaires (ex: claire/tiphaine).

**Comment by akkes** [comment]
Comme poste "Animateur informatique" correspondrait plus non?

**Comment by AlexFourgs** [comment]
Je rejoins @SnakeTGK95. Ce serait mieux de regrouper les personnes à un même niveau si elles ont un poste similaire pour que ce soit plus lisible.
Par exemple :
Alex, Julien, Arya, Sofiane
Claire, Tiphaine, Alexis, Johan
Bastien, Louis, Roxane, ?

**Comment by AlexFourgs** [comment]
@aryus96 on en est ou stp ?

**Comment by arya-coding** [comment]
Je suis d'accord pour l'ordre des postes. Alors j'ai fais 2 versions, vous me dites laquelle vous préférez.

![1232ere version](https://cloud.githubusercontent.com/assets/9800251/18417496/4f99bf6a-7832-11e6-9da1-e8123b1c0add.jpg)
![1ere version](https://cloud.githubusercontent.com/assets/9800251/18417508/854e82a8-7832-11e6-9328-f5dbb5611ab1.jpg)

**Comment by AlexFourgs** [comment]
La 1 est quand même pas mal.

**Comment by arya-coding** [comment]
Petit correction vice-secrétaire, et j'ai enlevé la ligne blanche sur la photo se sofiane.

![1ere version](https://cloud.githubusercontent.com/assets/9800251/18417769/587a37ca-7839-11e6-8c42-8a10cb2d4c4d.jpg)

**Comment by AlexFourgs** [comment]
Génial, je met sur facebook pour voir si ça convient à tout le monde ;)

Encore merci Arya !
