### ISSUE TITLE
Faire la demande de subvention pour Vendredi 23 Septembre

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#23]
**Vous trouverez le calendrier 2016 des demandes de subventions [ici](https://github.com/bdeecho/Meta/blob/master/Subvention/Calendrier%20%20CFVU%20et%20CVE%20%202016%20.pdf).
La demande de subvention vierge est téléchargeable [ici](https://github.com/bdeecho/Meta/blob/master/Subvention/Demande%20de%20subvention%20vierge.doc).
Les critères d'attributions des Fonds de Développement des Initiatives Étudiantes sont lisibles [ici](https://github.com/bdeecho/Meta/blob/master/Subvention/Crit%C3%A8res%20d'attribution%20FSDIE%2006-10-2015.pdf).**
# Sujet(s) de la demande de subvention
- Premier événement "Cadence" puisque la demande de subvention suivante sera trop tard. :x: 
- Régie DJ
- Aménagement local
# Premier "Cadence" :x:
## Listes des achats
- à faire avant tout
  - Faire très rapidement une estimation du nombre de participants pour avoir un devis pour le matériel
  - Trouver un lieu
  - Trouver les artistes
  - Trouver des partenariats (Chineurs de paname, surprize, ...)
- Communication (Flyers, affiches, etc...)
- Location matériel et prestation (sono + lumière + régie DJ)
- Gardiennage
- Cachet artistes 
## Justification(s)
# Régie DJ
## Liste des achats nécessaires
- 1ère option
  - 2*CDJ 900 NEXUS
  - DJM 850K
- 2ème option
  - 2*CDJ 900 NEXUS
  - Allen & Health XONE:92
- 3ème option
  - 1ère option
  - 2*Stanton ST150
- 4ème option
  - 2ème option
  - 2*Stanton ST150

**Prix neuf :**
1ère option : **4100€**
2ème option : **3725€**
3ème option : **5360€**
4ème option : **4985€**

**Prix occasion :** (Attention, les prix sont variables pour l'occasion)
1ère option : **3300€** _(-800€)_
2ème option : **3100€** _(-625€)_ 
3ème option : **4200€** _(-1160€)_
4ème option : **4000€** _(-985€)_
## Justification(s) de la nécessité des achats
- Cadence (option de secours).
- Afterwork Open Mix.
- Vente de gaufres avec mix.
- Local pour les adhérents.
# Aménagement local
## Liste des achats nécessaires
- Essayer de faire passer cafetière, bouilloire, micro-onde.
- SI REGIE DJ :
  - Grande étagère IKEA KALLAX qu'on peut coucher sur le côté
  - Petite étagère IKEA KALLAX qu'on peut coucher sur le côté (si platines vinyles)
  - Pied IKEA CAPITA

**Comment by arya-coding** [comment]
Pour la 1ère cadence, je vous laisse gérer toi et Julien. Toutefois, il ne faudra pas oublier le **prix des impressions d'affiches/flyers.**

Enfin, pour la déco du local, à la suite de la réunion avec la vie associative, nous saurons ce qui est possible ou non et je ferais un devis précis.

**Comment by AlexFourgs** [comment]
Bonne remarque pour la communication de l'événement ;)

**Comment by AlexFourgs** [comment]
MAJ Régie DJ + Aménagement local

**Comment by arya-coding** [comment]
Commentaire sur le prix du matériel DJ. Le prix me semble beaucoup trop élevé compte tenu des niveaux actuels des membres et de l'utilisation qui en sera faite (hors event, et encore, si j'ai bien compris certains de nos contacts ramèneront le matériel adéquate aux artistes lors des events). Du matériel de professionnel pour des semi-amateurs et amateurs totaux (De plus, la **pour le moment**, vous êtes 2-3 à mixer dessus, 5000€ pour 3 personnes...) ? 
Car là, si j'ai bien compris, on est sur les modèles haut de gamme, destiné à des boites de nuit etc, hors, je vous rappel que nous sommes une association étudiante et non pas un organisme lucratif à un large public.
Un set-up à 1500-2500€ ne suffirais t'il pas ? Je ne sais pas si vous vous rendez compte 4000-5000€ ?

Je sais que vous souhaitez vous faire plaisir et peser dans le game, mais autant d'argent pour cet équipement, même si central dans le BDE, n'est t'il pas abusé ?

La différence d'argent pourrait très bien servir à d'autres choses bien plus importantes.
Sinon il faudrait voir pour le rentabiliser. A faire les cadences payantes ou autres méthodes de renflouement, même si c'est la fac qui paie le matériel, c'est énorme comme prix et c'est vraiment dommage.

Je suis convaincu qu'avec du matos moins onéreux, nous pourrions faire des événement tout aussi important et cool.

Enfin, qu'avez vous prévu en cas de détérioration du matériel ? Il va être souvent déplacé, manipulé et sujet aux accidents des membres.

En plus les gars, quand c'est moi qui parle d'abus, c'est que vraiment y'a un stade qui a été atteint là Mdr

Avis strictement personnel et déni de toute provocation ou de mauvaise intention, je préfère le rappeler car je sais que remettre en question le set-up DJ touche directement le cœur de certains ici mdr.

**Comment by Uinelj** [comment]
C'est vrai que le matériel est très cher. 

Mais, tout d'abord, si on présente 5000€ et qu'on nous en donne 3000 on n'est pas bloqués, tandisque si on demande 3000 et qu'on nous donne 1700, là, ça va être difficile.. Donc on part sur des configurations haut de gamme pour ça notamment.

Ensuite, le matériel ne sera pas exclusif à Echo. C'est une question qui n'est pas encore déterminée, mais il va de soi que du matériel à 3000+€ doit être partagé pour être rentabilisé.

De plus, la valeur à la revente est assez peu désavantageuse pour nous, donc on peut renflouer en revendant.

Enfin, on a déjà présenté un budget de 3500€ à la vie associative, qui n'a pas été choquée, mais qui a préféré nous voir réussir un événement avant d'étudier la question.

Je sais que ça peut paraître énorme comme somme, mais c'est pas de l'argent dépensé dans un truc oneshot, c'est un investissement à long terme pour Echo et pour les gens qui veulent utiliser ce matos dans d'autres BDE ou dans le futur.

**Comment by Uinelj** [comment]
Pour revenir sur le budget, on peut économiser un peu sur la table de mixage en partant sur une [Xone43](http://www.sonovente.com/allen-heath-xone-43-p47077.html). Pour avoir mixé cet après midi dessus, elles font le boulot pour un setup turntable + CDJ.

On pourrait imaginer proposer un budget sans turntable pour économiser encore plus, et les prendre ultérieurement.

**Comment by arya-coding** [comment]
Mais si vous demandez 5000 et que vous avez 5000 ? Vous n'investirez que une part raisonable dans le matériel et l'autre part serait utilisée pour d'autres choses donc ?

C'est vrai que la valeur de la revente est intéressante, mais est-ce que l'on peut revendre le matériel d'une association ? Si oui, comment cela se passe ?

Et avec les set-ups que tu proposes Julien, de combien serait le prix ?

**Comment by Uinelj** [comment]
Si on présente notre setup à 5000€ et qu'on l'a, on est forcés d'acheter le matériel avec, à hauteur de 5000€.

Avec une 43 on économise 500€ par rapport à une 92.

**Comment by arya-coding** [comment]
Moi je suis vraiment contre un budget matériel de 4000 à 5000€.

Donc on pourrais faire descendre l'option 2 à 3225€. N'y a t'il pas un autre matériel où nous pouvons viser moins haut de gamme ?

**Comment by AlexFourgs** [comment]
Comme l'a dis Julien, de toute manière on va demander pour 5000€ de matos mais rien ne nous assure de l'obtenir. 

Ça nous coûte rien de poser les couilles sur la table et d'avoir le culot de demander. Au pire c'est refuser et tant pis, au mieux une partie ou la totalité est accepté et on a du bon matériel.

Pour un BDE qui se veut lié à la musique électronique et au mix c'est tout de même relativement intéressant d'avoir du vrai matériel tout le temps à disposition pour les adhérents et pour nos petits événements.

D'autres associations (Remed, Porta, Kiwi & inc) qui organisent des soirées dans des boîtes de nuit demandent bien entre 7000 et 10000€ de subvention pour ces mêmes soirées alors qu'il y a moins de défi à relevé, qu'il faut juste faire un chèque au patron de la boite. Nous on demande 5000€ pour du matériel qui servira à plusieurs (petits) événements et tout au long de l'année, personnellement, dans la logique des principes de notre association, je ne trouve pas ça choquant. Certes les chiffres sont peut-être ahurissant quand on est pas trop dans le délire, mais sinon ça me parait logique.

**Comment by arya-coding** [comment]
Oui mais si on obtiens 5000€ de matériel, tout mettre la dedans, c'est du gâchis selon moi.
Et si ils nous donne moins, par exemple, 4000€, le problème reste le même.

C'est clair qu'il faut du matériel pour l'association et du bon matériel, mais n'y a t'il pas un compromis entre prix & utilisation qu'il va en être fait ?

Ouai mais leur demande de subvention est faites pour 200 à 1200 étudiants.

**Comment by AlexFourgs** [comment]
Quand tu fais une demande de subvention tu dois fournir un bilan de la dernière demande de subvention.
Si on demande 5000€ de subvention pour une régie DJ et qu'on l'obtiens, on dépensera 5000€ pour une régie DJ c'est tout. On va pas commencer à faire des bails du style 4000€ pour une régie DJ et on se fait plaisir avec les 1000€ qu'il reste, on a pas le droit et ça poserai un problème point de vue confiance entre la fac et notre association.

Nous on parle de 3 à 6 événements (entre les Afterwork et les Cadences) + dans le local sur une année. Si tu additionne au final ça revient à faire une demande de subvention pour 900 à 2500 personnes, sur une seule année. Si on obtiens ce matériel cette année, on aura pas à le redemander l'année prochaine.

Comme l'a dis @Uinelj c'est du long terme aussi.

En fait, il faudrait croiser ça avec le prix que nous coûterait nos soirées.

**Comment by Uinelj** [comment]
J'ai pas d'objection à ce qu'on parte sur une régie un peu cheap, mais **si on demande 2000€ et qu'on nous en file 1400, on est baisés. C'est fini, pas moyen de composer avec si peu.** C'est ce qui est arrivé à Hazybot, et j'ai pas envie que ça nous arrive. Alors on demande 5000, et c'est à eux de nous dire "c'est du gâchis" ou pas. Et le matériel sera potentiellement partagé aux autres associations, je rappelle qu'il y a une asso qui fait du mix hiphop à la 33tour, etc.

**Comment by Uinelj** [comment]
J'ajoute aussi que l'université n'a pas ce genre de matériel. Donc l'acheter c'est aussi, potentiellement, le rendre accessible (sous conditions), à plein d'associations qui pourront en profiter.

**Comment by Uinelj** [comment]
@AlexFourgs Une thread reddit qui compare les Xone 43 et 92, en mettant l'accent sur la particularité des tables Xone, faites pour les longues transitions plutôt que pour les cuts sales.

https://www.reddit.com/r/Beatmatch/comments/3ym6rc/allen_and_heath_43_vs_92_xone/

**Comment by AlexFourgs** [comment]
J'ai l'impression que la 43 niveau boite à effet y'a rien...

**Comment by Uinelj** [comment]
C'est vrai, mais bon. Elle est pas chère et de bonne qualité. Elle nous suffira je pense..

**Comment by Eresia** [comment]
Je confirme que la fac ne donne **quasiment jamais** le montant demandé (sauf montant -1000€ ou événement très régulier comme les soirées de REMED et encore)
Donc il ne faut pas hésiter à demander. Et si par miracle vous les avez parce qu'ils sont à font avec vous, vous n'êtes pas obligé de tout investir dedans ! Il suffit de dire que vous avez trouvé une promo de genre 1000€ ou que avez trouvé la même en moins cher et que ça vous a permis d'économiser. En plus c'est bien vu

**Comment by Eresia** [comment]
Et insistez sur le partage ils aiment ça. Et s'ils veulent pas à cette sub discutez avec d'autres assoc intéressé pour faire une demande de sub à plusieurs

**Comment by Uinelj** [comment]
Merci infiniment pour ces conseils avisés :)

**Comment by Uinelj** [comment]
Update : Hérodote, MusicOs et AFAC sont chauds pour notre projet, ainsi que la fédé, potentiellement.Le matériel serait donc partagé (avec priorité pour Echo), et utilisé/utilisable par les adhérents de ces associations. Si on divise le coût (5k€) sur 4-5 associations déjà, c'est plus digeste.

**Comment by AlexFourgs** [comment]
On en a rediscuté un peu hier soir avec Julien. Il est possible que finalement on ne demande "que" 3000€ pour une table de mixage et deux platines cd. En effet, de un peu de personnes utilisent les platines vinyles, de deux on pense investir dans une ou deux platines vinyles avec les éventuelles bénéfices fait lors de nos événements cadence.

**Comment by arya-coding** [comment]
C'est raisonnable je trouve. Moi je suis pour. Toutefois, il faudrait demander plus, afin d'être sûr d'avoir les 3000€ non ?

**Comment by Uinelj** [comment]
Bonne remarque @aryus96 . On peut du coup demander une table de mixage un peu meilleure et rester sur des CDJ-900nexus ?

**Comment by arya-coding** [comment]
Au final on mettrais plus de 5000€ mais le budget sera étalé sur l'année et l'argent proviendra également des sous de l'association.

**Comment by Uinelj** [comment]
Si on inclut les platines vinyle carrément..

**Comment by AlexFourgs** [comment]
Suite à la réunion, du 16 septembre, on a plus besoin de demander quoi que ce soit pour la première Cadence puisque ce sera sur la subvention suivante étant donné qu'on change de date.

Donc le sujet de la demande de subvention sera pour la décoration du local. @aryus96 on te laisse gérer ça, fais nous une liste de courses propre comme tu l'avais fait avec une capture d'écran du panier avec leurs prix.
Et le matériel au local, @uj toi et moi on s'en occupe. On doit contacter rapidement Hérodote et AFAC pour avoir leur éventuelle soutien sur cette demande.

**Comment by AlexFourgs** [comment]
@aryus96 tu peux me faire le devis complet, genre une capture d'écran des produits finaux qu'on va mettre dans le demande stp
