### ISSUE TITLE
Faire des vêtements à l'image de l'association pour l'ensemble de l'équipe.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#25]
Je crée cette issue afin d'avoir votre avis sur l'idée. 

Aujourd'hui nous avons eu la journée de prévention des risques. L'animatrice à soulever un détail important, lors de ces soirées si une personne se sent mal il est important de pouvoir trouver et identifier un responsable (organisateur(s), quelqu'un qui a la formation des premiers secours, etc.) rapidement.

C'est pourquoi lors de nos événements il serait peut-être intéressant d'avoir des vêtements aux couleurs de l'association pour qu'on soit facilement identifiable.

Je vous laisse donner votre avis, on pourra discuter de ces vêtements en question si la majorité pense que c'est une bonne idée.

Je précise que du fait que ces vêtements ont d'abord comme premier but d'être facilement identifiable lors des événements et ainsi mieux gérer nos soirées, on fera tout ce qui est dans notre possible pour que vous obteniez chacun votre vêtement gratuit (aux frais d'Echo) bien entendu, ou que vous dépensiez le moins possible.

**Comment by Uinelj** [comment]
C'est une bonne idée ! A voir si on peut pas s'en occuper RAPIDEMENT, histoire que ça ne rajoute pas de tâches supplémentaires.

**Comment by arya-coding** [comment]
Pas de soucis. Je pense simplement à "STAFF" dans le dos derrière, et le logo sur la poitrine devant. Il nous faut quelquechose de peu cher, reconnaissable (donc on doit rester dans les standards).
Couleur blanche ? (Moins cher)

Je peux voir avec une entreprise "local" promediapub (dans ma ville, ne vous fiez pas au site, ils existent depuis 1987), l'avantage est qu'il n'y aura pas de frais de ports, on peut aller sur place tâter la marchandise et peu cher.

25 (commande minimale possible :/ ) t-shirt blanc **TTC** (sans flocage)  : 79,2€

**Comment by AlexFourgs** [comment]
25 t-shirt sans flocage 79€ ? Ça fait 3€ le t-shirt déjà c'est pas mal ! 
Et ça nous permettra d'avoir des t-shirts en réserve si on a du staff.

**Comment by arya-coding** [comment]
Oui, le textile est pas cher. Je peux faire une demande de devis dès que nous sommes fixés sur le modèle.

t shirt blanc / Logo poitrine et STAFF dans le haut du dos ?

**Comment by Uinelj** [comment]
T'as un mockup sous le coude ?

Sinon ça me semble très intéressant.

**Comment by arya-coding** [comment]
Voilà pour les mockups

![tshirt](https://cloud.githubusercontent.com/assets/9800251/18507384/6dd7e944-7a70-11e6-8c37-529f625775d2.PNG)
![capt1ure](https://cloud.githubusercontent.com/assets/9800251/18507385/6ef2db4a-7a70-11e6-8f0f-8f141e61c79a.PNG)

**Comment by Uinelj** [comment]
C'est par-fait !

**Comment by arya-coding** [comment]
J'envoie déjà ça pour un devis, pour voir ce que ca donne.

EDIT : J'ai envoyé la demande de devis, je reçois la réponse demain.

**Comment by AlexFourgs** [comment]
Génial ! Ça correspond parfaitement à l'idée que je me faisais des t-shirt !
