### ISSUE TITLE
Préparer la journée festive.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Meta#26]
On a besoin d'avoir un peu de visibilité sur la journée Festive.
# Ce dont on a besoin
- Enceinte BT
- Batterie de recharge téléphone
- PC Portable (Mon chromebook ?)
- Bannière
- Feuilles d'adhésion
- Caisse
# Diffusions
- Aftermovie Versity
- Cadence sauvage ?
- Boiler Room

Quoi d'autre ?

**Comment by AlexFourgs** [comment]
Ce dont on a besoin :
- Cartes de visites sur le stand + Distribution aux étudiants
- Post-it à mettre pour les éventuelles nouveaux adhérents

Diffusions :
- Pas d'électricité sur le stand, donc impossible de diffuser quoi que ce soit... Sauf sur un petit écran de PC portable et la batterie ne tiendra pas longtemps.

Il faut voir avec @Eresia si il peut coller son stand au notre et si il accepte qu'on empiète un peu sur le sien avec notre bannière de 3m ^^

**Comment by Eresia** [comment]
Faut voir

**Comment by arya-coding** [comment]
Rassure toi c'est juste la bannière qui empiétera, pas notre stand @Eresia.

Pour l'enceinte BT, j'en ramènerais une et je demanderais à Johan également (en cas de manque de batterie)
Je pourrais également prendre mon ordinateur.
Et j'ai quelques batterie de secours mais c'est vraiment pas le top.

**Comment by AlexFourgs** [comment]
Qui vient à quelle heure d'ailleurs ? Perso je compte y être à 8h30 max histoire d'être sûr d'avoir une bonne place et d'avoir le temps de monter un petit peu le "chantier" mdr

**Comment by arya-coding** [comment]
Moi plus vers 11h je pense.

**Comment by khodjas** [comment]
moi vers 12h

**Comment by clairengn** [comment]
Avec tiphaine on a que des TD ce jour la, c'est tendu de ne pas y aller. Mais on est dispo de 13:15-14:15 et a 15:45

**Comment by AlexFourgs** [comment]
Les horaires de la journée festive sont 11h 15h30 il me semble, si vous ne pouvez pas vous y rendre ce n'est pas grave ! ;)

**Comment by AlexFourgs** [comment]
Je pense qu'on peut clôturer ici non ?

En conclusion :
- On arrive vers 8h30 ( @Uinelj et moi ) pour obtenir un stand avantageux
- Bannière accroché/scotché à la table
- Cartes de visites
- Bonbons
- Formulaires d'adhésions
- Caisses
- Un pc portable pour éventuellement diffusé les aftermovies des LANs
- Musique grâce à @aryus96
