### ISSUE TITLE
Séparation des marques

### ISSUE THREAD

**Issue by akkes** [bdeecho/Meta#27]
Suites à différentes discussions avec @Uinelj et @AlexFourgs il est question de séparer les activités d'Echo de la manière suivante:
- _Versity_ pour la partie informatique (LAN/Hackathon/...)
- Cadence pour la partie musique (boiler/afterwork/...)
## Pour
- Indique clairement à quel type d'event on a affaire
## Contre
- Risque de créer une confusion entre les events (genre des gens qui viennent pour une LAN alors que c'est un hackathon)

n'hésitez pas à balancer vos arguments, ce sera MaJ au fil du temps

**Comment by AlexFourgs** [comment]
Dans un premier temps ce qui serait intéressant ce serait déjà de lister les différents events qu'on compte faire au cours de l'année :
- LAN
- Hackaton
- Cadence
- DEcadence/Apéro (Afterwork)

Du coup soit on décide de regrouper les événements similaire :
- Musique
  - Cadence
  - DEcadence/Apéro
- Informatique
  - LAN
  - Hackaton

Soit on part sur 4 événements distincts dans le sens ou il y en a que 4 ça ne pose pas trop de problèmes.
Tout se joue sur la communication après !

**Comment by akkes** [comment]
J'aimerai bien proposer des soirées ciné/débats avec des films comme citizen four

**Comment by AlexFourgs** [comment]
Hummm, je commence à me demander si il ne serait pas intéressant d'organiser une réunion pour le pole informatique d'Echo afin de voir ça tous ensemble.
J'avais oublié mais il y a aussi les events que Sofiane veut organiser, il faudrait une autre catégorie du coup.

**Comment by Uinelj** [comment]
Une autre catégorie ça commencerait à faire beaucoup, surtout si cela concerne des événements mineurs. 

Je vote pour nommer le pôle info Versity, le pôle musique  Cadence et garder les événements mineurs sous leur nom sans forcément avoir une catégorisation précise derrière.

**Comment by arya-coding** [comment]
Hors sujet : Mais bsartek le jeu de mot cadence/décadence.

**Comment by Uinelj** [comment]
Haha @aryus96 !

Pour préciser quelque chose : On a parlé avec la vie asso qui en a clairement MARRE des afterwork picole façon Remed. Donc on rename ça en décandences ou en apéro quelquechose, histoire de pas passer pour des trous à alcool auprès de la vie associative.

**Comment by AlexFourgs** [comment]
Apéro c'est sympa, ça fait conviviale alors que Afterwork c'est un peu le mot accrocheur fourre tout.
DEcadence c'est  bien pour le jeu de mot, mais Apéro c'est plus facile à comprendre que ça reste malgré tout, un afterwork en soit.

**Comment by Uinelj** [comment]
Après on peut titrer déCadence et en sous-titre mettre apéro open mix :)

**Comment by akkes** [comment]
En quoi ça concerne la vie asso si on fait ça en dehors de la fac sans leur financement?

Tu pourrais préciser ce que tu/la vie asso entend par "afterwork picole"?

**Comment by Uinelj** [comment]
En gros : 

La vie associative, et notamment un musicos qui est super hypé pour les Cadences, nous a dit qu'il en avait marre de voir des Afterwork. Tout le monde veut en faire, et ça rime souvent avec musique insipide et prétexte pour se bourrer la gueule. De plus, en général, les horaires de leurs afterwork sont 18h-00h, alors que normalement c'est du 17-20. 

Donc ça serait bien qu'on n'utilise pas le mot Afterwork pour deux raisons : 
- On dit explicitement que c'est PAS un afterwork, du moins pas comme les autres (musique > alcool)
- On est bien vus de la vie associative
- On se différencie des autres alors qu'on est potentiellement sur le même marché.

**Comment by akkes** [comment]
Le truc c'est qu'ils utilisent afterwork pour masquer le fait que ce soit une soirée. On cherche vraiment à en faire. Faudrait mieux ré-expliquer le concept à la vie asso. Limite on en fait hors bars avec des consoles/ordis avant d'en faire dans un bar

**Comment by AlexFourgs** [comment]
@akkes, t'inquiète, ils savent très bien ce qu'est véritablement un Afterwork et que les asso organisent tous des mini soirées qu'ils appellent Afterwork ;)

Nous on a bien préciser, on a la vie associative et la vie culturelle qui est de notre côté donc bon, c'est pas un problème t'inquiète ;)

Pour en revenir au sujet de cette issue, on sépare donc en 3 genres ?
- Musique qu'on appellerai "Cadence"
- Informatique qu'on appellerai "Versity"
- Divers

**Comment by akkes** [comment]
Je viens de penser à un problème: Versity n'est pas censé vraiment appartenir à Echo. Juste être le nom des LAN sur l'UCP. À mon que la LAN de life-up ai définitivement mit fin à cette idée?

**Comment by AlexFourgs** [comment]
Quel rapport avec Life-Up ?

**Comment by Uinelj** [comment]
LifeUp a eu un projet de LAN pendant un temps ! 

C'est pas un souci je pense, dans l'idée c'est Echo qui "pilote" Versity, qui potentiellement peut être adossé à d'autres assos.

**Comment by AlexFourgs** [comment]
Ah ok.

Bon décidez vous rapidement sur le sujet, c'est un peu une perte de temps ce débat amha.

**Comment by akkes** [comment]
@Uinelj du coup ça n'a pas eu lieu?

Même, dans ce cas ça veut dire qu'on oublie l'idée que c'est la marque des LAN sur l'UCP et ça devient la marque info d'Echo

**Comment by Eresia** [comment]
Que je sache quand Life Up ont voulu faire leurs LAN ils ne l'ont pas rattaché à Versity. Je pense que Versity est un vrai pôle d'Echo (les rageux diront que Phénix à sa part aussi)

**Comment by akkes** [comment]
C'est ce qu'il me semble être devenu la position, mais seulement de manière officieuse. D'où ma remarque puisque cela n'a pas été dit officiellement :-)

Ps: Nan, mais ça c'est un détail de l'histoire ;-)
