### ISSUE TITLE
tournoi de foot

### ISSUE THREAD

**Issue by khodjas** [bdeecho/Meta#28]
# Tournoi de foot
## Pourquoi ?

Sélection de membres de l’équipe de foot universitaire / Collecte de fonds soutien SOS enfants 
## Quand et où ?
- S’adresser au SUAPS, mairie, association sportive… pour solliciter l’accès a un terrain de foot (Maradas/Ponceau)
- 20 novembre : Journée internationale pour les droits de l’enfant 
- Solliciter les magasins de sports (Décathlon, Go sports, Courir) pour soutien 
## Comment ?
- Equipe : 8 joueurs
- Cotisation : 5e par joueur / 50e par équipe
- Spectateurs : 3e par personne
- Lots (gratuits ?) : récompense (place de cinéma, billet pour un match de foot)
## Organisation tournoi ?
- Première journée : Phase éliminatoires (12 équipes), matchs de 10 mins (one shot) / démarrage des poules
- Deuxième journée : 2 poules de 3 équipes, les 2 meilleurs se qualifie, demi-final (aller-retour) final (one shot – prolongation – tirs aux buts) – 10 min toujours 
## Equipements et personnel ?
- dossards
- Ballons
- 4 arbitres 
- 2 sécurité 
- 2 responsable déroulement 
- 2 stands accueils et rafraichissement

**Comment by AlexFourgs** [comment]
Reformater en Markdown, c'est plus lisible. Fais une autre issue pour les tables de ping pong qu'on mélange pas tout.
- Quand et ou
  - Voir avec la vie associative aussi si ils peuvent nous aider
- Equipement et personnel
  - La vie associative verra elle même les besoins nécessaire pour la sécurité

Éventuellement, est-ce que des sponsors pourrait nous fournir des dossards et ballon justement ? Ou est-ce qu'on doit l'ajouter à une demande de subvention ?

Pour la cotisation, les fonds seront reversé à une association ? Si c'est pas le cas je trouve ça chère perso, 5€ par jour + 50€ pour l'équipe.

**Comment by khodjas** [comment]
Arya avait poser la meme question pour les dossards et les ballons et je pense que le SUAPS pourrait nous les fournir.
Et la cotisation c'est 5e par joueur\* ou 50e par equipe ! (et oui c'est preferable qu'on trouve une association a qui les verser)

**Comment by Uinelj** [comment]
C'est pas un peu beaucoup 3€ pour les spectateurs ?

**Comment by AlexFourgs** [comment]
Ouai mais du coup si ils sont 8 par équipe, ça leur revient plus chère de s'enregistrer en équipe que chacun de leur côté.

Et ouai, faire payer les spectateurs je suis pas trop pour non plus, enfin à moins que ce soit dans la volonté de faire des dons à une organisation, mais j'pense faudrait les mettre moins chère dans ce cas la. Un euro symbolique, ou alors si c'est pour donner à une association caritative, tu leur dis de mettre ce qui veulent, mais c'est un euro min par exemple.

**Comment by Uinelj** [comment]
En général les dons c'est "au bon vouloir" des gens :)

**Comment by khodjas** [comment]
Euh au fait le tournoi risque de se faire beaucoup plus tot que prévu, ce qui veux dire mercredi 5 octobre. Les raisons etant : 
- d'une part vue que le tournoi a pour objectif de recruter des joueurs pour l'equipe universitaire, et vue qu'il y'a une date limite pour les inscriptions en compet en mi-octobre il faut bien que ca se fasse avant.
  -d'autre part le mercredi car il s'agit deja d'un chrenau pour notre universite le prof de foot est pret a nous accorder un terrain pour ce faire.

**Comment by khodjas** [comment]
- Ah oui pour les spectateurs c'etais juste une idee mais comme Arya a dis au pire on leur fait pas payer du tout. 
- Pour les equipes aussi on peut ne pas leur faire payer mais je trouvais ca interessant d'apporter une deuxieme cause carritative au tournoi; en ce qui concerne les choix de prix j'ai juste voulu faire rond ! 
  Donc au pire 5e par joueur 25e par equipe (c'est 7 joueurs par equipe au final)

**Comment by AlexFourgs** [comment]
Du coup tu as trouvé un terrain ?

5 Octobre ? ça va être tendu pour démarcher des sponsors en deux semaines mais on va faire ce qu'on peut ! ;)
Du coup c'est pareil niveau communication on va pas trop pouvoir faire des miracles, deux semaines ça veut dire on oublie affiches & inc, on les aura jamais à temps et puis même si c'est le cas mettre des affiches 2 jours avant le jour J ça sert pas à grand choses :/

Du coup finalement t'a besoin de quoi avec les nouvelles avancées ? Est-ce réellement nécessaire la sécurité ?

**Comment by Uinelj** [comment]
Il y a une histoire de rendez-vous ce soir @khodjas ?

**Comment by khodjas** [comment]
Les gars désolé pour le manque d'informations de ma part mais les choses se sont faites trop vite en ce qui concerne ce tournoi. 
Du coup au final avec L'ASUCP on a réussi à gérer l'organisation mais au niveau de la com c'est chaud encore. 
Est ce que vous êtes toujours dispo pour aider au déroulement ou vous ees assez dépassés comme ça ?
