### ISSUE TITLE
Identifier nos besoins niveau site web.

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Meta#3]
Il nous faut absolument trouver une liste relativement exhaustive des features dont on a besoin pour Echo cette année, on pourrait en discuter ici.
- Une page "vitrine", montrant un peu l'idée derrière Echo
- Une page "Vitrine" pour Versity, et une pour les Boiler
- Un µ-backoffice pour pouvoir gérer les inscriptions, tout ça.. 

Ensuite ? Ca serait cool d'avoir peut-être un interfaçage avec les issues github..

**Comment by AlexFourgs** [comment]
On en est ou du coup ?

**Comment by Uinelj** [comment]
Le développement a commencé : http://github.com/Moussaillons/Moussaillon

**Comment by AlexFourgs** [comment]
GENIAL ! Tu pourra mettre des screen de l'avancement ici stp ?
N'hésiter pas à voir avec Arya pour d'éventuelle graphisme.

**Comment by Uinelj** [comment]
C'est @akkes qui s'occupe de tout ça. Le site proposera un templating donc on sera libre de ce côté là.

**Comment by Uinelj** [comment]
Moussaillon tombant à l'eau, on devrait juste évoluer sur un site à moitié statique avec un backoffice simple ? @akkes chaud pour faire un Moussaillon avec moins de features ?

**Comment by AlexFourgs** [comment]
A voir si on a rééllement besoin d'un site ?
Qu'est-ce qu'il nous permettrait de faire ?

Parce que en soit, mis à part avoir une billetterie dessus, j'en vois pas trop l'utilité. Facebook nous sert déjà de vitrine pour l'actualité de l'asso, la comm'. Donc un site finalement... C'est stylé, ça peut faire croire que tu pèse un peu auprès des étudiants et des autres associations, mais sinon...

**Comment by akkes** [comment]
C'est utile pour présenter l'event de manière propre. (cf. le [site de versity](http://versitylan.com)) Faut voir si on peut faire un truc équivalent sur fb.

@Uinelj de ce que tu me décris, faut juste un kirby et un design. Pas besoin de faire un cms

**Comment by AlexFourgs** [comment]
On avait pensé à prendre le DNS bdeecho et de regrouper dessus une sous page versity (bdeecho/versity) et une page cadence (bdeecho/cadence). Du coup dans ce cas la oui ce serait intéressant !

**Comment by Eresia** [comment]
En vrai, Studeal permet déjà de faire ça les gros

**Comment by arya-coding** [comment]
Je pense qu'on se rajoute une charge de travail qui au final ne sera pas si utile.
Pour la LAN, certes, car il y a pas mal d'info, mais une boiler/cadence... Je pense que Facebook serait plus simple.
Merci du lien @Eresia.

**Comment by Uinelj** [comment]
On a @akkes qui pourrait potentiellement nous faire un site vitrine pour l'asso.

L'intérêt c'est d'avoir un backoffice pour pouvoir potentiellement diversifier nos activités !
Avoir une plateforme pour poster les replays des cadences sauvages, donner des informations plus générales, etc.

Ca pourrait aussi valoir le coup d'avoir une page "Projets" où on détaille Versity (LAN, HACK) et Cadence (sauvage, décadence, etc).

**Comment by akkes** [comment]
Un site vitrine et un back-office c'est complètement différent:
- L'un est un site quasi-statique avec juste ce qu'il faut pour pouvoir ajouter/modifier des éléments (exemple: le site du depinfo ou du cmi ou un portfolio)
- L'autre est un mini-ERM, c'est ce que Moussaillon (RIP) devait être et ce que fait StuDeal.

De ce que je lis tu veux un site vitrine, pas un back-office. Hormis pour l'upload des cadences j'ai du mal à voir en quoi fb suffit pas ;-)

**Comment by Uinelj** [comment]
Concrètement FB risque de takedown, sur notre site c'est moins probable ? 
Après niveau répercussions d'un côté t'as un takedown de ta page, de l'autre une action en justice...
Peut-être qu'on pourrait essayer YouTube ?

**Comment by Uinelj** [comment]
Et concernant le mini-ERM, j'ai rien de fixé dans la tête mais je me dis que ça pourrait être utile..

**Comment by arya-coding** [comment]
Pour le replay de nos cadences, sur youtube on aura le même problème de droits que FB ?

**Comment by Uinelj** [comment]
Je sais que YT est moins regardant si tu monétise pas tes vidéos, et si ta chaîne est plus petite. Bien qu'il y ait un robot derrière... Au pire mixcloud ;)

**Comment by akkes** [comment]
Sinon Snapchat? On y diffuse la tracklist, vu que diffuser les cadences c'est pas le but premier

**Comment by Uinelj** [comment]
L'idée serait de pouvoir browse entre les différentes cadences. Je pense que mixcloud serait plus intéressant ! On perd la vidéo mais bon, on a la tracklist et moins de risques niveau droits.

**Comment by arya-coding** [comment]
Hmmm chacun à ses avantages. Je serais partant pour un mixcloud, mais pour la vidéo, on mets toujours sur FB quitte à ce qu'on se fasse supprimé la vidéo.
Mais pour FB, on devrait faire des vidéos de 2-3minutes de chaque cadences, ton idée était pas mal @Uinelj

**Comment by Uinelj** [comment]
J'ai peur qu'on se fasse takedown la page en fait :(

**Comment by AlexFourgs** [comment]
Je pense pas que ta page se fait takedown comme ça, il y a des avertissements avant.
- YouTube pourquoi pas, on peut passer entre les mailles du filet et le partager sans risque sur Facebook.
- Mixcloud on aura aucun problème mais comme tu l'a souligné il y aura la vidéo en moins.
- @Uinelj vérifie sur le site que tu m'avais envoyé, ça se peut que ce soit un mixcloud-like avec la vidéo en plus, donc théoriquement ils ont pas de problèmes niveau droits.

**Comment by Uinelj** [comment]
@aryus96 Merci beaucoup ! Ca donne quoi Audiowide avec juste la première lettre en capitale ?

**Comment by arya-coding** [comment]
@Uinelj  noob

**Comment by Uinelj** [comment]
:(

**Comment by AlexFourgs** [comment]
Du coup le DN versitylan.com se termine dans quelques jours.

On renouvelle l'abonnement avec le DN bdeecho.com qui regroupera les différentes informations que ce soit Cadence ou Versity ? (du genre bdeecho.cadence.com, bdeecho.versity.com ou une connerie dans le genre)

**Comment by akkes** [comment]
@AlexFourgs Ce ne serait pas plutôt cadence.bdeecho.com et versity.bdeecho.com ?

**Comment by AlexFourgs** [comment]
Ouai ^^

**Comment by AlexFourgs** [comment]
Mais du coup ça répond pas à la question x)

On reprend un nom de domaine pour un site général avec des sous domaines pour versity et cadence ?

**Comment by akkes** [comment]
J'y suis favorable.

Juste que si on lâche versitylan.com risque d'y avoir du cyber squatting donc on risque de ne pas pouvoir le récupérer. Éventuellement le réserver un an de plus en redirect le temps que le lien soit dé-référencé partout?

**Comment by Uinelj** [comment]
Je sais pas si on risque vraiment le cybersquatting..

Franchement peu importe, c'est 9€..

**Comment by akkes** [comment]
Les estimateurs donnent 0€ donc pas besoin de le garder en fait

**Comment by Eresia** [comment]
En vrai pour le prix, balek
