### ISSUE TITLE
Trouver un nom pour le concept "Boiler"

### ISSUE THREAD

**Issue by Uinelj** [bdeecho/Meta#4]
Il faudrait discuter du potentiel nom de l'event, et rapidement histoire de pouvoir élaborer le logo, les affiches, etc.

**Comment by AlexFourgs** [comment]
Pour le nom : J'aimerai qu'on mette en avant l'UCP. Faudrait trouvé un jeu de mot avec UCP d'après moi, ou alors avec Echo (même si le nom de l'assoc' joue déjà en notre faveur)
Pour le logo : On devrait faire des variantes avec le logo Echo en fonction des événements.

Je pense qu'il est important de jouer avec le nom du BDE et son logo, histoire d'en faire une marque de fabrique et que lorsque que les étudiants verront nos affiches et le noms des événements, ils sachent que c'est Echo qui en est l'origine :)

**Comment by Uinelj** [comment]
Jeu de mot avec UCP pourquoi pas mais c'est fait encore et encore en fait.. Pas mal d'assos ont ucp dans leur nom, et j'ai peur que ça nous relègue un peu au statut de "pauvre asso étudiante" :/

Il faut trouver un truc un peu trendy, qui renvoit une image un peu "underground", mais pas trop.

**Comment by AlexFourgs** [comment]
Alors un jeu de mot avec Echo ? Je donne ces idées d'un point de vue un peu commercial hein. Lorsque les étudiants se diront y'a tel événements, faut que le nom de l'assoc' ressorte en même temps si tu vois ce que je veux dire. Soit on se fait un nom avec des événements qui marque la vie étudiante (des événements qui font du bruit), soit dès le départ il faut un nom qui rime avec Echo en gros.

On oublie UCP ;)

**Comment by Uinelj** [comment]
Avec Echo oui, pourquoi pas ! On peut aussi jouer sur un truc qui identifie la fac, quelque chose qui la distingue du reste.  Il faut réfléchir à des noms, des mots, qui évoquent l'univers de l'électro et des soirées perchées, sans pour autant oublier la fac.

**Comment by AlexFourgs** [comment]
Les Echosphères ? La pour le coût c'est perché mdrrr

**Comment by AlexFourgs** [comment]
Le nom trouvé est : "Cadence"
