### ISSUE TITLE
Remplir le tableau de renseignement.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#5]
A remplir par tous les membres du bureau et à renvoyer à Valérie Rame.

**Comment by Uinelj** [comment]
Il faut renvoyer un tableau rempli avec le nom des collaborateurs d'Echo (je propose d'ailleurs qu'on définisse ce terme comme étant la liste des gens faisant officieusement partie d'echo et aidant aux projets, sans être liés par une inscription à la préfecture).

**Comment by AlexFourgs** [comment]
Corrigé.
