### ISSUE TITLE
Établir le calendrier des événements.

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#6]
- Lister les événements :heavy_check_mark: 
  - 2 Lans :heavy_check_mark:
  - 3 Boiler Room : [Infos](https://github.com/bdeecho/Chaudiere/blob/master/Boilers.md) :heavy_check_mark: 
  - Voyages ? :x: 
  - Déplacements Festivals Electro :heavy_check_mark: 
    - Établir un calendrier des festivals électro sur toute l'année et prendre contact.
- Choisir les dates :exclamation: 
  - LANS
    - Décembre
    - ?

**Comment by Uinelj** [comment]
Concernant les Boiler room allons discuter sur [chaudiere#3](https://github.com/bdeecho/Chaudiere/issues/3).

**Comment by AlexFourgs** [comment]
En ce qui concerne les autres événements ? On valide 3 Lans déjà ? Les voyages ? Et les déplacements aux festivals + achat groupé d'entrée ?

**Comment by Uinelj** [comment]
T'es sûr que c'est pas trop ?

**Comment by AlexFourgs** [comment]
Up !
3 Boiler, 2 Lans ?
- Organisation d'achat groupé pour les festivals ? (ça c'est pas grand chose, se renseigner si y'a pas des tarifs de groupes et éventuellement prendre contact avec les organisateurs des festivals)

**Comment by Uinelj** [comment]
Ok pour moi. Deux LAN c'est pas mal ! Et ça colle avec les deux vacances de 2 semaines.
