### ISSUE TITLE
Établir une liste des effectifs nécessaire pour l'année prochaine. (Rôle + nombre)

### ISSUE THREAD

**Issue by AlexFourgs** [bdeecho/Meta#7]
_Format_
Rôle : Nombre minimum (+ au mieux)

Je met à jour au fur et à mesure de vos propositions.
- Général
  - Community Manager : 1 
  - Staff événements : 8 (+ 7)
  - Photographe : 1 (+ 1) :heavy_check_mark: 
  - Secrétaire : 1 :heavy_check_mark: 
  - Trésorier : 1 :heavy_check_mark: 
  - Graphiste : 1 :heavy_check_mark: 
- Boiler Room
  - DJ "Résident" : 1 (+ 1)
- Versity

**Total : 16 (+ 13)**

**Comment by AlexFourgs** [comment]
Update

**Comment by Uinelj** [comment]
Ca me paraît être un bon début. Par contre, je suis pas sûr qu'on doive vraiment compter le staff comme ça. On peut se donner comme but d'en avoir 10, mais je préfère avoir 8 "gars sûrs" que 12 mecs qui sont là pour une tise gratos. Il faudrait commencer à voir dans nos relations universitaires si il n'y aurait pas des gens chauds.

**Comment by AlexFourgs** [comment]
Euuh, quand je parle de staff je parle pas de mec qui font acte de présence pendant les événements perso, faudra les briffer la dessus et bien expliquer aux personnes qui s'engage ce que c'est d'être membre du staff.

Moi le staff je le voyais plus à l'image d'hôtesse qui accueil les étudiants à l'entrée de l'événement par exemple (c'est un peu cliché mais bon), qui s'occupe au bon déroulement de la soirée en aidant à droite à gauche...

**Comment by Uinelj** [comment]
Yep, c'est ce que je voulais dire.

**Comment by AlexFourgs** [comment]
Il nous restent à trouver du staff, un community manager, un secrétaire ainsi que un ou deux photographes.

**Comment by AlexFourgs** [comment]
Up ! On devrait peut-être balancer une annonce sur FB et demander à la page de la vie associative de la partager non ?

**Comment by Uinelj** [comment]
Yep ! Avec un message du genre :

"L'association >Echo fait peau neuve et recherche du staff pour des évènements tournant au tour des jeux vidéo, mais aussi de la musique électronique !  Féru de soirées house et techno ? Habitué des LAN Parties ? Ou simplement enthousiaste à l'idée de participer à un projet associatif de grande envergure ? Contacte-nous sur Facebook !"

**Comment by AlexFourgs** [comment]
Mec, t'es aussi admin de la page, n'hésite pas ! Et je pense que t'a plus l'âme community manager que moi, tu écris mieux :)

**Comment by AlexFourgs** [comment]
Et oublie pas qu'on recherche pas seulement du staff, mais aussi des photographes (1 ou 2) et un community manager (à moins que tu veux qu'on s'en occupe).

**Comment by Uinelj** [comment]
Ok, je custom le message soon then

**Comment by AlexFourgs** [comment]
Du coup on a besoin que de staff maintenant je pense ?

**Comment by Uinelj** [comment]
Comment ça ?

**Comment by AlexFourgs** [comment]
Personnel présent pendant les événements pour l'organisation :
- Gestion du vestiaire
- Gestion de l'entrée (billet etc...)
- Gestion du bar
- Gestion général (guidé les participants pendant la soirée, s'assurer que tout se passe bien).

Si on regarde tout ça, je dirais minimum 10 personnes nécessaire voir 15, sans oublier qu'on fera nous même partis de ce staff.

**Comment by AlexFourgs** [comment]
Bon je clôt cette issue. Il ne nous reste que du staff à recruter pour les jours d'événements.
